/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LOGICA_CODIGO;

import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Joseph F
 */
public class SeleccionarColor extends javax.swing.JFrame {

    private Carta.Color comodin = null;
    Boolean permitido = false;
    PopUp popup;
    
    
    public SeleccionarColor() {
        initComponents();
    }
    
    public SeleccionarColor(PopUp pop){
        initComponents();
        popup = pop;
    }
    
    public Carta.Color escoger(Carta carta){
        if(carta.getColor() == Carta.Color.Morado){
            this.setVisible(true);
            this.setResizable(false);
            this.setBounds(100, 150, 600, 700);
        }
        return carta.getColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rojo = new javax.swing.JButton();
        verde = new javax.swing.JButton();
        amarillo = new javax.swing.JButton();
        azul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione el color de su Comodin");

        rojo.setText("Rojo");
        rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoActionPerformed(evt);
            }
        });

        verde.setText("Verde");
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });

        amarillo.setText("Amarillo");
        amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarilloActionPerformed(evt);
            }
        });

        azul.setText("Azul");
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verde, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(azul, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(azul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verde, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoActionPerformed
        comodin = Carta.Color.Rojo;
        JLabel mensaje = new JLabel("El color del juego es Rojo!");
        mensaje.setFont(new Font("Arial", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null, mensaje);
        permitido = true;
        this.dispose();
        popup.ColorDeclarado = Carta.Color.Rojo;
        popup.gamestage.PonerCodigoJugadores(popup.juego.ObtenerJugadorActual());
        popup.gamestage.ponerIconoBotones();
        popup.BotonCartaTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Small/" + popup.juego.ObtenerImagenCartaSuperior())));
        popup.juego.setColorCarta(Carta.Color.Rojo);
        popup.dispose();
    }//GEN-LAST:event_rojoActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        comodin = Carta.Color.Azul;
        JLabel mensaje = new JLabel("El color del juego es Azul!");
        mensaje.setFont(new Font("Arial", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null, mensaje);
        permitido = true;
        this.dispose();
        popup.ColorDeclarado = Carta.Color.Azul;
        popup.gamestage.PonerCodigoJugadores(popup.juego.ObtenerJugadorActual());
        popup.gamestage.ponerIconoBotones();
        popup.BotonCartaTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Small/" + popup.juego.ObtenerImagenCartaSuperior())));
        popup.juego.setColorCarta(Carta.Color.Azul);
        popup.dispose();
    }//GEN-LAST:event_azulActionPerformed

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeActionPerformed
        comodin = Carta.Color.Verde;
        JLabel mensaje = new JLabel("El color del juego es Verde!");
        mensaje.setFont(new Font("Arial", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null, mensaje);
        permitido = true;
        this.dispose();
        popup.ColorDeclarado = Carta.Color.Verde;
        popup.gamestage.PonerCodigoJugadores(popup.juego.ObtenerJugadorActual());
        popup.gamestage.ponerIconoBotones();
        popup.BotonCartaTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Small/" + popup.juego.ObtenerImagenCartaSuperior())));
        popup.juego.setColorCarta(Carta.Color.Verde);
        popup.dispose();
    }//GEN-LAST:event_verdeActionPerformed

    private void amarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarilloActionPerformed
        popup.ColorDeclarado = Carta.Color.Amarillo;
        popup.gamestage.PonerCodigoJugadores(popup.juego.ObtenerJugadorActual());
        popup.gamestage.ponerIconoBotones();
        popup.BotonCartaTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Small/" + popup.juego.ObtenerImagenCartaSuperior())));
        popup.juego.setColorCarta(Carta.Color.Amarillo);
    }//GEN-LAST:event_amarilloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amarillo;
    private javax.swing.JButton azul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton rojo;
    private javax.swing.JButton verde;
    // End of variables declaration//GEN-END:variables
}
